apiVersion: v1
kind: Service
metadata:
  name: esphome
  namespace: home-assistant
  labels:
    app: esphome
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6052
    targetPort: 6052
    protocol: TCP
  selector:
    app: esphome

