apiVersion: v1
kind: Service
metadata:
  name: esphome
  namespace: home-assistant
  labels:
    app: esphome
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 6052
      nodePort: 30652
      protocol: TCP
  selector:
    app: esphome

