apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - httproutes-media.yaml
  - httproutes-infra.yaml
  - httproutes-storage.yaml
  - external-docker-services.yaml

