apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgCgAeiBoXSBaOgn8EechDkBoG77jkHzEtKxqC+fBc1UOTvca48sFefAgf1TfXQpHltxe3Ph4uUoD5OMoSZwrurTIXx9ST0zYiFg8fGvsCIyLpbGV2YG+D4H+m/VI6bom00mGY57IocWo+CbufbijTq8udgCjZEWEJnsfoPbveGozpAWXifwvbBMBh9kGW2P6TNlRvyGG/HO4Fxo635BHfqWC3CBK+zD3dqijN8Mufe6yGc6Hao08R74QpYYexsCNYwuGUSUgh5vCtD+ePpypvPO9ymTkn6pQGH+pV1fhlaelfVIdEBcGQiJFFQPC4IdntBv80HYGHRSFU1+vL3Umy62akg2KSJjTmRsHMAdvAzz4DEztn/0wo+a1LSq9Cr8ai5L65H9+h0iPBUyAuvOJJqYx7eria21f0AXh4C+eiV/zqDaMFH/64jgQdIzGFv6uoEE4qFmXJT4c2jMJlCO7QmdU2uF0exZCdCRFtnoGmZGJbW1aMw9XeAN2WRUacG5251gmBYhto4aBp7SzFTKi9cjC0acpQXsk9STplxhxwGEIW/bdE0AvdDB6PDyUrQtPke1yvf/h9PYMIH8n2GyhLqqOSjpdMpbfnLWP9bpoo4DhxsBZBRwJlAXs9OYFBQoR77UHaMOf2HHFVzIdsK57Mj/Gpi3lUpwWLar1Fz6iS1BgIL+nG/4QQB+6XdhfGbCic8qlr1CAYhntf4cfi65w1k91BnlpPGGNlaase0Fqw1fAqEvJf1xq+iQY0E06B1s
  template:
    metadata:
      name: alertmanager-telegram-secret
      namespace: monitoring
