apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgAi770xo6fElHzVEQK1nl+R3bToqopUgKoncTA64dDM7qoV0ffNrmQC5DTPfyIID7g4BUid7j1uNbOwomWXhotOBfkAgTtdti+m+6D8QLS80dxb7/I2d5pJAuhTo4P32yqFOj7RE76+sET1cVpN+TnbHqHT5PBVxQ2OiHcwJaOlg2g+j5f2NG7aVbnL4ulgHD5uTeylWbC4wew4ZjtqnWrEZXt9rfhWEPLwVUX9NkccKiaVzSGR75I1yvke9tApEh2s1hDNr5a9nTtiHmZACVh85Rr+WKOiO5aEpbPJxrhTNsNZRfJM6TihAEia0eDsnkqADR9jWVLUIdxr0Ca6pLqL+oblXiOa5yFqydVgUS+MFKJuVdewZLN7oxvtIEXnegKWj2V0zzLSoTc9GTAlSkcVK2M1HUJEm0jJSv/hBGTui5epmOj2ydRKOJcsHtIlTQ4T1OHisutJYA0M+4Kt+8Q/cQTFL9nIENG9iPAD5kmOnsyG6zo8KYMp7KfHCmsVkXAckiSEFGyjDabiSZ1q+Ou4rbWnWMXsUcoSDyMyOx7FpCauMhdlIIfystEUfQzB1V6V0V4m70WYccRwb3iztpp8qboS77zE/8qowJ6C349Bnj2mdKa7WuQBXzEqkWajJS8+HJGZRknRpAZV2O73NjKmcCdRiXOqA8l9juzMucVwWAKE6oQdaR5jIfFWXxE6vBG5N97anVWfQ3+6ikYMSTTHYfWgQOPi0Edam+hATZ9rbI+8Maf3j148R+eNKyIH
  template:
    metadata:
      name: alertmanager-telegram-secret
      namespace: monitoring
